### ISSUE TITLE
Android Studio 3.x / Gradle 4.x compatibility

### ISSUE THREAD

**Issue by Gounlaf** [galex/android-permissions-gradle-plugin#2]
Hi,

With last Android Studio (3.0 Canary 5), using Gradle 4.1, I got this error:

> Error:Could not get unknown property 'manifestOutputFile' for task ':app:processDebugManifest' of type com.android.build.gradle.tasks.MergeManifests.

Could you take a loot at it?

Thanks,
Regards

**Comment by galex** [comment]
@Gounlaf Thank you so much for this bug report! 

I just fixed the issue and deployed it to jcenter as version **1.1.0**.
I'll be happy if you could confirm that it works for you too. 

Thanks!

**Comment by Gounlaf** [comment]
It seems to be OK @galex :)

Thanks !
